### ISSUE TITLE
Peaks as reactive data option?

### ISSUE THREAD

**Issue by rowild** [oncletom/vue-waveform-template#1]
I am trying to understand how Peaks works in this Vue example. It seems that `peaks` is not available on Vue's `data` options. Or am I mistaken?

Here is what I did in order to make `peaks` to `data`:

I tried to move the cues-generating part of the `onWaveformLoaded` to its own function `showCues` and call that one from a button event listener:

```js
export default {
  data () {
    return {
      peaks: null
    }
  },
  mounted() {
    document.querySelector('[data-action="show-cues"]').addEventListener('click', () => {
      this.showCues();
    });
  },
  methods: {
    onWaveformLoaded(error, peaks) {
      [...]
      this.peaks = peaks
    },
    showCues () {
      this.cues.forEach(cue => this.peaks.points.add(cue))
      this.peaks.on('points.dragmove', ({ id, time:newTime }) => {
        const time = parseFloat(newTime.toFixed(4))
        this.$store.commit('programme/cueUpdate', { id, time })
      })

      // Test: log out `this._waveform`
      console.log("this._waveform =", this._waveform)
    },
  }
}
```

This makes it work for this scenario. But I wonder, if this is the way to go. I have no idea what `this._waveform` is actually doing. Logging it out at the end of `showCues` only results in `undefined`. 

I wanted to have the `destroy` function available as a separate function (n case it is needed somewhere else) and did this:

```js
beforeDestroy () {
  this.destroyWaveform()
},
methods: {
    destroyWaveform () {
      this._waveform.destroy()
    }
}
```

However, `this_waveform` is not available, the console throws this error.

```js
Uncaught TypeError: Cannot read property 'destroy' of undefined
```

Any thoughts on what I am doing wrong?

**Comment by thom4parisot** [comment]
Have you checked the `error` in the `onWaveformLoaded()`? Perhaps something went wrong, especially if you have not referenced the DOM elements assigned to the waveforms.

I have written a working Vue.js template here: https://github.com/oncletom/vue-waveform-template/

_EDIT_: actually, it sounds you may have taken your example from this template. A few notes:

- `this._waveform` is assigned after the `mounted()` Vue event, to avoid Vue observing Peaks properties — same effect as the underscore prefix (`_`). I don't have a use case in mind which makes property tracking useful here.
- thus, you have a mismatch between `this.peaks` (where you assign the Peaks instance, reactive) and the events which refer to `this._waveform` (non-reactive)

**Comment by rowild** [comment]
@oncletom yes, my question are in regard to your template :-) I was very happy, when I found that! Love to experiment with web audio.

However, there are some things, that I still do not understand. May I ask some more questions, please?

If you have no reactive `peaks` object, how do you assign, delete and manage in general (new) points (`cues` in your case, I believe)? Always calling the onWaveformLoad os probably not it.

As for the wavefrom snippet, my setup does not change your setup; and neither in mine nor in your version `this._waveform` logs to the console. (I also remove `this.peaks = peaks`...) How can I reach `this._waveform`? I want to see what's in it.

```js
    this.$nextTick(() => {
      this._waveform = Peaks.init({
        ...defaultOptions,
        mediaElement: this.$refs.audioPlayer,
        dataUri: this.$props.dataFile,
        containers: {
          overview: this.$refs.overview,
          zoomview: this.$refs.zoomview
        },
        keyboard: true,
        pointMarkerColor: '#006eb0',
        showPlayheadTime: true,
        zoomLevels: [256, 512, 1024, 2048, 4096]
      }, this.onWaveformLoaded)

      console.log('$nextTick: this._waveform =', this._waveform);
    })
```

BTW: the DOM is referenced correctly.

Keeping your setup, but separating the destroy function into its own method like shown above still does not work - and I do not see the difference between my

```js
mounted() {
  someBtnEl.addEventListener('click', ()=> {
    this._waveform.destroy()
  })
},

methods: {
  destroyed () {
    this.destroyWaveform()
  },
}
```

and your

```js
methods: {
  destroyed () {
    this._waveform.destroy()
  }
}
```

? Any help would be much appreciated!

**Comment by rowild** [comment]
If i use 
```js
    destroyWaveform () {
      this.peaks.destroy()
    }
```

then the waveform disappears. But I still have no idea what the function of `this._waveform` is, since it console-ouputs `undefined`, even though it should be "something".

Any advice on how to properly setup a peaks instance as a reactive data property?

BTW: Using your setup as it is throws an error in the `destroyed` hook when hot-reloading:
`TypeError: Cannot read property 'destroy' of undefined.`

**Comment by thom4parisot** [comment]
I think their purpose is the same, and the `this.peaks` of your example is the `this._waveform` of this template:

https://github.com/oncletom/vue-waveform-template/blob/0487c39751d6a677dfdf44cda5274b68faa41499/src/components/Waveform.vue#L50-L58

I should have stated this template is a work-in-progress :-D

The strategy I imagine to manage the data:

- _not_ storing the peaks instance as a reactive variable
- storing temporal data as reactive data/store data
- using `vuex` `subscribe()` listener would enable to add/remove data from the waveform

**Comment by rowild** [comment]
Of course I tried to replace `this._waveform` with `this.peaks`, but that's wrong. `this.peaks = peaks` has to be assigned in `onWaveformLoader`.

Did you test your code? Do you get usable info in the console for `this._waveform`?
My hunch is that `this._waveform` is not needed or should be assigned somewhere else, maybe also in `onWaveformLoader`...

**Comment by thom4parisot** [comment]
I have added a new commit, with clearer name, and the ability to add new points.

**Comment by rowild** [comment]
Wow! Very exciting! Thank you! 

Haven't looked at the intro/extro track feature, but it seems only the intro will render an audio tag when a song is selected?

And I want apologise for my stupidity; I really want to learn, so I tend to get on people's nerves! And I wonder if you could help me understand this weird `this._peaks` property. I simply do not get a useful `console.log()`, it is undefined. Even when I remove the underline and write `this.peaks`.

I understand that you do not want to put it into $data because it would be turned into a reactive object. So you define the propery somewhere else, in this case on `methods()`. To test, if I would see anything at all, when I logout other properties, I defined 2 more, `this.mainSong` (right after `mounted()`), and `this.favouriteSalsa`(within $nextTick()).

```js
  mounted () {
    this.mainSong = 'Nessun dorma'

    this.$nextTick(() => {
      this.favouriteSalsa = 'Pedro Navaja'

      // We store the Peaks instance when the DOM is ready
      this._peaks = Peaks.init({
        ...defaultOptions,
        mediaElement: this.$refs.mainTrack,
        dataUri: {
          arraybuffer: this.$props.dataFile
        },
        containers: {
          overview: this.$refs.overview,
          zoomview: this.$refs.zoomview
        }
      }, this.onWaveformLoaded)

      console.log('this._peaks =', this._peaks); // undefined

      console.log('this.mainSong =', this.mainSong); // 'Nessun dorma'
      console.log('this.favouriteSalsa =', this.favouriteSalsa); // 'Pedro Navaja'
    })
  },
```

Both give me the content of the property, when logged out, when written with underscore, `this._mainSong` and `this._favouriteSalsa`.

So I keep wondering, why `this._peaks` is undefined? Should there be at least SOME kind of result since it is defined at that moment, when logged out?

Thank you for your patience!!!

**Comment by rowild** [comment]
When I set `this._peaks = peaks` within `onWaveformLoaded`, then it works (also the `destroy` function):

```js
onWaveformLoaded (error, peaks) {
      if (error) {
        throw new Error(error)
      }
      this.peaks = peaks
      this.peaks.zoom.setZoom(3)
    }
}
```

**Comment by thom4parisot** [comment]
Okay, it took me a while to realize `Peaks.init()` did not return anything at all.

I have adjusted the template accordingly.

Thank you for your patience 😅
