### ISSUE TITLE
"Vue.set" in "store/programme.js" does not work with Nuxt.js

### ISSUE THREAD

**Issue by rowild** [oncletom/vue-waveform-template#2]
To update cues, Vue.set is used:
https://github.com/oncletom/vue-waveform-template/blob/main/src/store/modules/programme.js#L37-L39

This does not work in Nuxt.js, unless "export const strict = true" is set in "store/index.js" (vuex standard folder in nuxt).

I posted this problem on the Vue Forums:
https://forum.vuejs.org/t/nuxt-2-vuex-updating-an-object-within-an-array-with-vue-set-throws-error/125558

I hope this finds an answer, and if so, it should probably be mentioned in this excellent template!

**Comment by thom4parisot** [comment]
Well, there is also this warning you shared:

> [vuex] do not mutate vuex store state outside mutation handlers.

I will have a look to see how to do it.

**Comment by rowild** [comment]
Exactly. This warning happens due to the Vue.set, which is inside the `updatePoint` function. (And, also as mentioned: it disappears when `strict` is set to `false`.)
I think it has to with my setup: I set attr which are not yet declared (your func instead only sets 2 already declared attributes). I'll report back, when I am at the computer again...

**Comment by rowild** [comment]
It was indeed the problem of trying to update not-yet existing attributes. Reducing the update object to only the attributes that will be updated, does not throw that error. 

Sorry for fast-shooting! Everything is fine, so I close this comment again, hope this is all right with you.

**Comment by thom4parisot** [comment]
Okay no problem, it saves me time as if I understand well, I have nothing to investigate.

Have fun :-)
